force-app/main/default/objects/Event_Details__c/Event_Details__c.object-meta.xml
<CustomObject>
    <label>Event Details</label>
    <nameField>
        <label>Event Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Details__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <inlineHelpText>Enter Event End Date/Time</inlineHelpText>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Event_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_Date_Time__c</fullName>
    <inlineHelpText>Enter Event Start Date/Time</inlineHelpText>
    <label>Event Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Event_Description__c.field-meta.xml
<CustomField>
    <fullName>Event_Description__c</fullName>
    <inlineHelpText>Enter Event Description</inlineHelpText>
    <label>Event Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Event_Ticket_Price__c.field-meta.xml
<CustomField>
    <fullName>Event_Ticket_Price__c</fullName>
    <label>Event Ticket Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Static_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Static_Image_URL__c</fullName>
    <label>Static Image URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Venues__c.field-meta.xml
<CustomField>
    <fullName>Venues__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Venues</label>
    <referenceTo>Venues__c</referenceTo>
    <relationshipLabel>Event Details</relationshipLabel>
    <relationshipName>Event_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Venues__c/Venues__c.object-meta.xml
<CustomObject>
    <label>Venues</label>
    <nameField>
        <label>Venues Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Venues__c/fields/Event_Details__c.field-meta.xml
<CustomField>
    <fullName>Event_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Details</label>
    <referenceTo>Event_Details__c</referenceTo>
    <relationshipLabel>Venues</relationshipLabel>
    <relationshipName>Venues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EventController.cls
public class EventController {
    @AuraEnabled(cacheable=true)
    public static List<Event_Details__c> getPastEvents() {
        return [SELECT Id, Name, End_Date_Time__c, Event_Date_Time__c, Static_Image_URL__c, Venues__r.Name 
                FROM Event_Details__c 
                WHERE End_Date_Time__c < TODAY 
                ORDER BY End_Date_Time__c DESC LIMIT 4];
    }
    @AuraEnabled(cacheable=true)
    public static List<Event_Details__c> getUpcomingEvents() {
        return [SELECT Id, Name, Event_Date_Time__c, Static_Image_URL__c, Venues__r.Name 
                FROM Event_Details__c 
                WHERE Event_Date_Time__c > TODAY 
                ORDER BY Event_Date_Time__c DESC LIMIT 4];
    }
    @AuraEnabled(cacheable=true)
    public static List<Event_Details__c> getEventDetails(Id eventId) {
        return [SELECT Id, Name, Event_Date_Time__c, Static_Image_URL__c, Venues__r.Name, Event_Description__c 
                FROM Event_Details__c 
                WHERE Id = :eventId LIMIT 1];
    }
    @AuraEnabled(cacheable=true)
public static List<Event_Details__c> findEventsByName(String eventName) {
    String searchKey = (eventName != null && eventName.trim() != '') ? ('%' + eventName + '%') : '%';

    return [SELECT Id, Name, Event_Date_Time__c
            FROM Event_Details__c
            WHERE Name LIKE :searchKey
            AND Event_Date_Time__c <= TODAY
            ORDER BY Event_Date_Time__c DESC
            LIMIT 10];
}

     
@AuraEnabled(cacheable=true)
public static string ticketprice(Id EvtId , String ticketType ,Integer numTickets){
    
    Event_Details__c Evt = [SELECT Id, Event_Ticket_Price__c 
    FROM Event_Details__c 
    WHERE Id = :EvtId LIMIT 1];

if (Evt == null ) {
System.debug('No concert found');
return null ; // Return 0 if no concert found
}
Decimal calculatedPrice = Evt.Event_Ticket_Price__c; // Default price

// Apply Ticket Type logic
if (ticketType == 'VIP') {
calculatedPrice *= 1.5 * numTickets;
} else if (ticketType == 'Student') {
calculatedPrice *= 0.85 *numTickets;
}
if (ticketType == 'General') {
calculatedPrice *= 1 *numTickets;
} 

System.debug('Final Calculated Price: ' + calculatedPrice);
return String.valueof(calculatedPrice);
}

}