force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account the quote is associated with.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <label>Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <description>The opportunity the quote is associated with.</description>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/GenerationOfQuotationPDFApexClassTest.cls
@isTest
public class GenerationOfQuotationPDFApexClassTest {
    @isTest
    public static void method1(){
        Account ac = new Account();
        ac.Name='test acc';
        insert ac;
        
        Opportunity opp = new Opportunity();
        opp.Name='test opty';
        opp.CloseDate=date.today();
        opp.StageName='Qualification';
        insert opp;
       
        Quote__c qc = new Quote__c();
        qc.Email__c='test@stetig.com';
        qc.Account__c=ac.Id; 
        qc.Phone__c='+91 9876543210';
        qc.Opportunity_Name__c=opp.Id;
qc.Created_Date__c = System.today();
        insert qc;
        
        GenerationOfQuotationPDFApexClass.sendemailmethod(qc.Id);
    }
    
    
}